### ISSUE TITLE
about ACDC 

### ISSUE THREAD

**Issue by AustinYuAo** [asif-hanif/vafa#1]
Disturbed the author!
Thank you for making your code public. Can you introduce the preprocessing process of the ACDC dataset?

**Comment by asif-hanif** [comment]
Hi @AustinYuAo 

Thanks for showing interest in our work.

We followed the same preprocessing steps as used by [UNETR++](https://github.com/Amshaker/unetr_plus_plus). Please refer to `Dataset` section of the [UNETR++](https://github.com/Amshaker/unetr_plus_plus). It should be noted that voxel values of ACDC dataset are NOT in the range of `[0,1]`. Therefore, we used a normalization function which transforms the voxel values to the range of `[0,1]` so that attack could be performed in standard settings.
